### ISSUE TITLE
Awesome Books morning session review

### ISSUE THREAD

**Issue by Sly-Cloud** [AmineHLub/Awesome-books#9]
### Project looks good

Well done on implementing the needed functionalities, but as for the navigation and the `Add new` button, I'm suggesting you use `display: none` and `display: block` in your CSS to make things easier for yourself

**Comment by alexander16108** [comment]
good job  on implementing the required functionalities and I'm more Impressed with how good the code is, It nice and easy to understand and navigate through 

Cheer and Happy coding
